# Generated by Django 4.2.10 on 2024-11-22 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/', verbose_name='ファイル'),
        ),
    ]
