# Generated by Django 4.2.10 on 2024-11-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_diary_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='diary',
            name='price',
            field=models.CharField(blank=True, max_length=40, verbose_name='値段'),
        ),
    ]
